name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  python_ci:
    name: Python CI
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - uses: actions/checkout@v3

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          architecture: x64
          enable-pep582: true
      
      - name: Install deps
        run: |
          pdm install
      
      - name: Format check
        uses: jpetrucciani/black-check@master
